"""Canonical 24-feature contract between the trained XGBoost model and live MLCN flows.

This module is the single source of truth for what the model expects.
``data/common_feature_schema.json`` (generated by ``data/common_feature_schema.py``)
documents the same contract and takes its units and types from here.

Evidence (``Untitled-1.ipynb`` + ``MachineLearningCVE/*.csv``):

* The model was trained on the raw CIC-IDS2017 MachineLearningCVE columns
  (CICFlowMeter output). No scaling or transformation was applied; NaN/inf in
  ``Flow Bytes/s`` / ``Flow Packets/s`` were median-filled, rows with negative
  durations were dropped, and features were cast to float32.
* ``Flow Packets/s == packets / (Flow Duration / 1e6)`` for every row, so all
  time features are **microseconds** while rates are **per second**.
* Packet lengths are **transport payload bytes** (TCP/UDP payload, including
  any Ethernet padding Scapy exposes after the transport header).
* ``Packet Length Mean/Std`` are computed over ``n + 1`` values because
  CICFlowMeter adds the first packet's payload twice.
* ``Down/Up Ratio == floor(backward / forward)`` (integer division).
* The six ``* Flag Count`` columns are binary and describe only the **first
  packet** of the flow, with CICFlowMeter's permuted bit mapping
  (see :data:`CIC_FLAG_COLUMN_SOURCE`). Verified with ``Init_Win_bytes_forward``:
  ``PSH Flag Count`` rows carry SYN windows, ``FIN Flag Count`` rows carry
  RST windows (0), UDP rows are all zero.
* ``Active Mean`` / ``Idle Mean`` only record periods split by a gap
  > 5,000,000 µs; the trailing active period is never added, and the FIN
  packet that terminates a flow does not update active/idle state.
* Flows terminate on the first FIN packet (CICFlowMeter 2017 behaviour) or
  after 120 s from flow start; no training row has fewer than 2 packets.
"""

from __future__ import annotations

from dataclasses import dataclass

MICROSECONDS_PER_SECOND = 1_000_000

ACTIVITY_TIMEOUT_SECONDS = 5.0
ACTIVITY_TIMEOUT_MICROSECONDS = int(ACTIVITY_TIMEOUT_SECONDS * MICROSECONDS_PER_SECOND)

# CICFlowMeter flow timeout used for CIC-IDS2017 (measured from flow start).
FLOW_TIMEOUT_SECONDS = 120.0

# CIC-IDS2017 flows end on the first FIN packet seen in either direction.
TERMINATE_FLOW_ON_FIN = True

# Training data contains no flow with fewer than two packets.
MIN_FLOW_PACKETS = 2

# CICFlowMeter only produced flows for TCP and UDP.
CLASSIFIED_PROTOCOLS: frozenset[str] = frozenset({"TCP", "UDP"})

# Training replaced NaN/inf rates (zero-duration flows) with the dataset medians
# computed after de-duplication (notebook cells 23-30).
ZERO_DURATION_RATE_FILL: dict[str, float] = {
    "Flow Bytes/s": 3715.0378579999997,
    "Flow Packets/s": 69.742244285,
}

# Model column -> Scapy TCP flag letter of the FIRST packet that sets it to 1.
CIC_FLAG_COLUMN_SOURCE: dict[str, str] = {
    "FIN Flag Count": "R",
    "SYN Flag Count": "P",
    "RST Flag Count": "C",
    "PSH Flag Count": "S",
    "ACK Flag Count": "A",
    "URG Flag Count": "F",
}


@dataclass(frozen=True)
class FeatureSpec:
    name: str
    unit: str
    dtype: str  # "int" or "float"
    formula: str


FEATURE_SPECS: tuple[FeatureSpec, ...] = (
    FeatureSpec("Flow Duration", "microseconds", "int", "last_ts - first_ts"),
    FeatureSpec("Total Fwd Packets", "packets", "int", "packets in first-packet direction"),
    FeatureSpec("Total Backward Packets", "packets", "int", "packets in opposite direction"),
    FeatureSpec("Fwd Packets Length Total", "payload bytes", "int", "sum fwd payload"),
    FeatureSpec("Bwd Packets Length Total", "payload bytes", "int", "sum bwd payload"),
    FeatureSpec("Fwd Packet Length Mean", "payload bytes", "float", "fwd payload / fwd packets"),
    FeatureSpec("Bwd Packet Length Mean", "payload bytes", "float", "bwd payload / bwd packets"),
    FeatureSpec("Flow Bytes/s", "payload bytes per second", "float", "payload / (duration_us / 1e6)"),
    FeatureSpec("Flow Packets/s", "packets per second", "float", "packets / (duration_us / 1e6)"),
    FeatureSpec("Flow IAT Mean", "microseconds", "float", "mean gap between packets"),
    FeatureSpec("Flow IAT Std", "microseconds", "float", "sample std of gaps"),
    FeatureSpec("Fwd IAT Mean", "microseconds", "float", "mean gap between fwd packets"),
    FeatureSpec("Bwd IAT Mean", "microseconds", "float", "mean gap between bwd packets"),
    FeatureSpec("Packet Length Mean", "payload bytes", "float", "mean of [first] + all payloads"),
    FeatureSpec("Packet Length Std", "payload bytes", "float", "sample std of [first] + all payloads"),
    FeatureSpec("FIN Flag Count", "binary", "int", "first packet has RST"),
    FeatureSpec("SYN Flag Count", "binary", "int", "first packet has PSH"),
    FeatureSpec("RST Flag Count", "binary", "int", "first packet has CWR"),
    FeatureSpec("PSH Flag Count", "binary", "int", "first packet has SYN"),
    FeatureSpec("ACK Flag Count", "binary", "int", "first packet has ACK"),
    FeatureSpec("URG Flag Count", "binary", "int", "first packet has FIN"),
    FeatureSpec("Down/Up Ratio", "ratio", "float", "floor(bwd packets / fwd packets), 0 if no fwd"),
    FeatureSpec("Active Mean", "microseconds", "float", "mean active period closed by idle gap"),
    FeatureSpec("Idle Mean", "microseconds", "float", "mean gap > 5 s"),
)

FEATURE_ORDER: tuple[str, ...] = tuple(spec.name for spec in FEATURE_SPECS)
FEATURE_COUNT = len(FEATURE_ORDER)
FEATURE_UNITS: dict[str, str] = {spec.name: spec.unit for spec in FEATURE_SPECS}
INTEGER_FEATURES: frozenset[str] = frozenset(
    spec.name for spec in FEATURE_SPECS if spec.dtype == "int"
)
TIME_FEATURES: frozenset[str] = frozenset(
    spec.name for spec in FEATURE_SPECS if spec.unit == "microseconds"
)
